# Generated by Django 4.1.1 on 2022-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=50)),
                ('movie_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('villian', models.CharField(max_length=50)),
                ('phase', models.IntegerField()),
            ],
        ),
    ]
